### ISSUE TITLE
Memory error when synchronising longer texts

### ISSUE THREAD

**Issue by ext666** [EtienneAb3d/WhisperTimeSync#2]
Hi, when I try to sync subtitles longer than about 30 minutes, WhisperTimeSync gives me the following error:

```
at com.cubAIx.WhisperTimeSync.CubaixAlignerSimple.align(CubaixAlignerSimple.java:42)
at com.cubAIx.WhisperTimeSync.CubaixAlignerSimple.syncMarks1to2(CubaixAlignerSimple.java:16)
at com.cubAIx.WhisperTimeSync.WhisperTimeSync.process(WhisperTimeSync.java:48)
at com.cubAIx.WhisperTimeSync.WhisperTimeSync.main(WhisperTimeSync.java:91)
```

I solve it by splitting the subtitles into two parts, but it's not very convenient.

**Comment by EtienneAb3d** [comment]
@ext666 

Yes, as said at the bottom of the ReadMe, this aligner is RAM-consuming and time-consuming for large files.

But, you can increase the amount of RAM available to the JVM to a higher value (2G in the command line sample), depending on the machine capability:

`java -Xmx2G -jar ...
`

It should be sufficient for your case.

**Comment by ext666** [comment]
Works perfectly, thank you!
